#!/bin/bash
#apptrackr app links fetcher module for bashIRC
#Requires bashIRC 0.2.3 or newer.
if [ "$(type)" = "PRIVMSG" ]; then
   cmd=$(text | awk '{print $1}')
   if [ "$cmd" = "@links" ]; then
      if [ "$(text | awk '{print $2}')" ]; then
         id=$(text | awk '{print $2}')
         bastard=$(curl "http://ax.phobos.apple.com.edgesuite.net/WebObjects/MZStoreServices.woa/wa/wsLookup?id=$id" | sed -e 's/[{}]/''/g' | awk -v k="text" '{n=split($0,a,","); for (i=1; i<=n; i++) print a[i]}' | grep '"trackName":' | sed 's/:/ /1;s/"//g' )
         
         if [ -z "$bastard" ]; then
            notice $(nick) Error: No such application
         else
            notice $(nick) Grabbing top 7 links for app ${bastard#* * }...
            results=$(curl -d "request=%7B%22request%22%3A%22%7B%5C%22object%5C%22%3A%5C%22Link%5C%22%2C%5C%22action%5C%22%3A%5C%22get%5C%22%2C%5C%22args%5C%22%3A%7B%5C%22app_id%5C%22%3A$id%7D%7D%22%7D" http://api.apptrackr.org)
            parsed=$(echo "$results" | sed -e 's/[{}]/''/g' | awk -v k="text" '{n=split($0,a,","); for (i=1; i<=n; i++) print a[i]}' | sed -e 's/\\//g;s/:/=/g' | tr '}', '\n' | tr '{', '\n')
            idlist=$(echo "$parsed" | grep '"id"=' | head -n 10 > /tmp/idlist)
            
            while read shit; do
               data=$(echo "$parsed" | grep -A6 "$shit" > /tmp/data)
               x=1
               while read data; do
                  if [ "$x" = "6" ]; then
                     sleep 1
                     notice $(nick) Ver: $version .:. Cracker: $cracker .:. URL: http:$url
                     break
                  fi
                  brix=$(echo "$data" | sed -e 's/=/ /g')
                  brix1=$(echo "$brix" | awk '{print $1}' | sed -e 's/"//g')
                  brix2=$(echo "$brix" | awk '{print $2}' | sed -e 's/"//g')
                  if [ "$brix1" = "cracker" ]; then
                     cracker="$brix2"
                  fi
                  if [ "$brix1" = "version" ]; then
                     version="$brix2"
                  fi
                  if [ "$brix1" = "url" ]; then
                     url=$(echo "$brix" | awk '{print $3}' | sed -e 's/"//g')
                  fi
                  x=$((x+1))
               done < /tmp/data
            done < /tmp/idlist
         fi
      fi
   fi
   
fi



